config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  # 検索
  get "search" => "searchs#search"
  # カテゴリータグ
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

resources :messages, only: [:create]
resources :rooms, only: [:create,:show]

# ゲストログイン設定
devise_scope :user do
  post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book


  # １つのコメントに対しいいねを重複できない状態に制限
  validates :user_id, uniqueness: {scope: :book_id}

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.erb
<!-- いいね機能 -->
<span id="favorite_btn_<%= book.id %>">
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorite_path(book), method: :delete, remote: true do %>
      ブックマーク:♥<%= book.favorites.count %> 
    <% end %>
  <% else %>
    <%= link_to book_favorite_path(book), method: :post, remote: true do %>
      ブックマーク:♡<%= book.favorites.count %> 
    <% end %>
  <% end %>
</span>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render 'favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render 'favorite-btn', book: @book) %>");