config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  # 検索
  get "search" => "searchs#search"
  # カテゴリータグ
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

resources :messages, only: [:create]
resources :rooms, only: [:create,:show]

# ゲストログイン設定
devise_scope :user do
  post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  # 相互フォローチャットルームの中間テーブル
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # フォローした関係
  # アソシエーションが繋がっているテーブル名、class_nameは実際のモデルの名前、foreign_keyは外部キー
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされた関係
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー一覧
  # has_many :テーブル名, through: :中間テーブル名, source: :参照するカラム
  has_many :followings, through: :relationships, source: :followed
  # フォロワー一覧
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  # nameは検索対象であるusersテーブル内のカラム名
  # % → 0文字以上の任意の文字列 （例）#{word}% → 前方一致
  # whereメソッドを使いデータベースから該当データを取得
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def favotited_by?(book_id)
    favorites.where(book_id: book_id).exists?
  end

  def get_user_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width,height]).processed
  end

  # ゲストユーザー設定
  # find_or_create_by：データの検索と作成を自動的に判断して処理を行う、Railsのメソッド
  # find_or_create_by!の「!」を付与することで、処理がうまくいかなかった場合にエラーが発生
  # SecureRandom.urlsafe_base64：ランダムな文字列を生成するRubyのメソッド
  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # ゲストユーザー判定
  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/seesion_controller.rb
class Users::SessionsController < Devise::SessionsController
　# ゲストログイン用コントローラー

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 # ゲストログイン用コントローラー

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @book_comments = BookComment.new
    @yesterday_book = @books.create_yesterday
    @this_week_book = @books.create_this_week
    @last_week_book = @books.create_last_week
    
    # 相互フォローチャットルーム作成
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @obj = @user  #エラー表示用
    if @user.update(user_params)
      flash[:notice] =  "You have updated user successfully."
      redirect_to users_path
    else
      render template: "users/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
 
  # 与えられたIDを持つユーザーを検索し、そのユーザーが現在のユーザーであるかを確認
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  # ゲストユーザーはプロフィール編集画面へ遷移できない
  # "guest_user"はモデルで設定（ゲストユーザー判定）
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
       flash[:alert] = "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      redirect_to user_path(current_user)
    end
  end  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_btn.erb
<% if user.present? %>
  <% if current_user != @user %>
    <% if current_user.following?(user) %>
     <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn btn-success" %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_user_image(50, 50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_user_image(100, 100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>フォロー数:  <%=link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
  <th>フォロワー数:  <%=link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<!-- ゲストユーザーの時にはユーザーのプロフィール編集ボタンを表示させない -->
<% unless current_user.guest_user?%>
  <div class="row">
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  </div>
<% end %>

<!-- 現在のユーザーと表示対象のユーザーが異なる場合にフォローボタンを表示し、同じ場合はユーザーのプロフィール編集ボタンを表示 -->
<!--<% if current_user != @user %> -->
   <!--<td><%= render "users/follow_btn", user: user, options: { class: ""} %></td> -->
   <!--<% else %> -->
   <!--<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %> -->
    <!--<i class="fas fa-user-cog"></i> -->
    <!--<% end %> -->
 <!--<% end %> -->

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <!-- ユーザー情報 -->
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <!-- 新規投稿フォーム -->
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
     <!-- ユーザー一覧 -->
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <!--ユーザー情報 -->
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <!-- 相互フォローのときにチャットルーム作成-->
      <% unless @user.id == current_user.id %>
      <% if (current_user.following?(@user)) && (@user.following?(current_user))  %>
      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
        <% end %>
      <% end %>
      <% end %>
    <% end %>

      <!--新規投稿フォーム -->
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <!--投稿一覧 -->
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>