config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  # 検索
  get "search" => "searchs#search"
  # カテゴリータグ
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

resources :messages, only: [:create]
resources :rooms, only: [:create,:show]

# ゲストログイン設定
devise_scope :user do
  post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :category,presence:true

  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  
  # いいねが多い順並び変え用
  # -> { ... }  関連付けに特定の条件を指定
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'

  # 投稿を新着順・いいねの多い順に並び替え機能
  scope :latest, -> { order(created_at: :desc)}
  scope :favorites, -> { order(favorites: :desc)}

  scope :create_today, -> {where(create_at: Time.zone.now.all_day)}
  scope :create_yesterday, -> {where(create_at: 1.day.ago.all_day)}
  scope :create_this_week, -> {where(create_at: 6.day.ago.at_beginning_of_day..Time.zone.now.end_of_day)}
  scope :create_last_week, -> {where(create_at: 2.week.ago.at_beginning_of_day..1.week.ago.end_of_day)}
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  # titleは検索対象であるbooksテーブル内のカラム名
  # % → 0文字以上の任意の文字列 （例）#{word}% → 前方一致
  # whereメソッドを使いデータベースから該当データを取得
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  has_one_attached :profile_image

end

app/models/category.rb
class Category < ApplicationRecord

  validates :category, presence:true

  has_many :books, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  # ユーザーとチャットルームの中間テーブル(room管理）

  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book


  # １つのコメントに対しいいねを重複できない状態に制限
  validates :user_id, uniqueness: {scope: :book_id}

end

app/models/message.rb
class Message < ApplicationRecord
  # ユーザーとチャットルームの中間テーブル(message管理）

  #メッセージが空白の場合、保存されない
  validates :message, presence: true
  
  belongs_to :user
  belongs_to :room

end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  # フォローするユーザーのidとの関連付け
   belongs_to :follower, class_name: "User"
  # フォローされるユーザーのidとの関連付け
   belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
  # 相互フォロー同士のチャットルーム
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  # 相互フォローチャットルームの中間テーブル
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # フォローした関係
  # アソシエーションが繋がっているテーブル名、class_nameは実際のモデルの名前、foreign_keyは外部キー
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされた関係
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー一覧
  # has_many :テーブル名, through: :中間テーブル名, source: :参照するカラム
  has_many :followings, through: :relationships, source: :followed
  # フォロワー一覧
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  # nameは検索対象であるusersテーブル内のカラム名
  # % → 0文字以上の任意の文字列 （例）#{word}% → 前方一致
  # whereメソッドを使いデータベースから該当データを取得
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def favotited_by?(book_id)
    favorites.where(book_id: book_id).exists?
  end

  def get_user_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width,height]).processed
  end

  # ゲストユーザー設定
  # find_or_create_by：データの検索と作成を自動的に判断して処理を行う、Railsのメソッド
  # find_or_create_by!の「!」を付与することで、処理がうまくいかなかった場合にエラーが発生
  # SecureRandom.urlsafe_base64：ランダムな文字列を生成するRubyのメソッド
  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # ゲストユーザー判定
  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seesion_helper.rb
module SeesionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<!-- booknewの時も反応してしまうから要検討 -->
<!-- <% if obj && obj.errors.any? %> -->
  <!-- <div id="error_explanation"> -->
  <!-- <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3> -->
    <!-- <ul> -->
    <!-- <% obj.errors.full_messages.each do |message| %> -->
        <!-- <li><%= message %></li> -->
        <!-- <% end %> -->
    <!-- </ul> -->
    <!-- </div> -->
    <!-- <% end %> -->

<% if flash[:notice].present? %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container">
    <a class="navbar-brand" href="/">
      <img src="<%= asset_path('logo.webp') %>" alt="サイトロゴ" class="logo-image">
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> about
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> signup
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <!DOCTYPE html>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <html lang="ja">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/41e38c5826.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <!-- CSS only（モーダル用） -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper（モーダル用） -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/errors', obj: @obj if @obj.present?%>
    <!-- ワード検索/カテゴリー検索機能(ログイン時のみ表示) -->
    <div class="search-var">
      <table class="search-var">
        <% if user_signed_in? %>
          <tr>
          <td><%= render 'searchs/search'%></td>
          <td><%= render 'tagsearches/tagsearch' %></td>
          </tr>
        <% end %>
      </table>
    </div>
      <main>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>